/**
 * ترجمات موثوق - العربية، الفرنسية، الإنجليزية
 * Mawthooq i18n: AR, FR, EN
 */
window.MAWTHOOQ_T = {
  ar: {
    brand_name: "موثوق",
    nav_home: "الرئيسية",
    nav_about: "من نحن",
    nav_services: "خدماتنا",
    nav_how: "آلية العمل",
    nav_contact: "اتصل بنا",
    nav_scan_btn: "امسح منتجك",
    hero_title: "تحقق من منتجاتك",
    hero_title_highlight: "في لحظات",
    hero_sub: "باستخدام منصة موثوق، امسح رمز QR على أي منتج غذائي أو تجميلي لتعرف مدى أصالته وسلامته. نحن نحميك من المنتجات المغشوشة والخطرة.",
    hero_scan_btn: "امسح المنتج الآن",
    hero_how_btn: "كيف تعمل",
    hero_stat1: "أكثر من 10 آلاف منتج موثّق",
    hero_stat2: "دقة عالية",
    scan_badge: "الماسح الضوئي",
    scan_title: "امسح رمز QR للمنتج",
    scan_sub: "وجّه الكاميرا نحو رمز QR على العبوة للتحقق من المنتج",
    scan_status: "جاري المسح... ضع رمز QR داخل الإطار",
    scan_result_label: "نتيجة المسح:",
    scan_not_found: "المنتج غير مسجّل في قاعدة بيانات موثوق.",
    scan_again_btn: "مسح رمز آخر",
    scan_camera_hint: "يعمل أفضل على HTTPS أو localhost",
    scan_error_hint: "تأكد من منح الموقع صلاحية الكاميرا أو جرّب متصفحاً آخر (Chrome / Edge).",
    scan_err_generic: "حدث خطأ. تحقق من الاتصال أو جرّب لاحقاً.",
    scan_err_no_camera_support: "المتصفح لا يدعم الكاميرا. استخدم Chrome أو Safari على جهازك.",
    scan_err_libs_not_loaded: "لم يتم تحميل مكتبات المسح. تحقق من الاتصال بالإنترنت.",
    scan_err_video_failed: "تعذّر تشغيل الفيديو. تأكد من السماح للكاميرا.",
    scan_err_permission_denied: "تم رفض صلاحية الكاميرا. السماح من إعدادات المتصفح.",
    scan_err_camera_not_found: "لم يتم العثور على كاميرا.",
    scan_err_camera_unreachable: "تعذّر الوصول للكاميرا. جرّب HTTPS أو متصفحاً آخر.",
    hero_card_tagline: "منتج غذائي · شوكولاته",
    hero_card_status: "✔ أصلي",
    hero_card_title: "شوكولاته داكنة",
    hero_card_bullet1: "خالٍ من الدهون المهدرجة",
    hero_card_bullet2: "قد يحتوي على مكسرات",
    hero_card_verified: "تم التحقق عبر موثوق",
    how_badge: "منظومة متكاملة",
    how_title: "كيف يعمل موثوق؟",
    how_sub: "ثلاث خطوات بسيطة للحصول على معلومات دقيقة عن أي منتج",
    how_step1_title: "افتح الماسح",
    how_step1: "اضغط على زر المسح الضوئي داخل التطبيق أو الموقع.",
    how_step2_title: "امسح رمز QR",
    how_step2: "وجّه الكاميرا نحو الملصق الموجود على العبوة.",
    how_step3_title: "تحقق واطلع",
    how_step3: "تظهر لك معلومات شاملة: المكونات، المخاطر، وتعليمات الاستخدام.",
    how_detail_badge: "دليل الاستخدام",
    how_detail_title: "آلية العمل خطوة بخطوة",
    how_detail_step1_title: "افتح الماسح",
    how_detail_step1: "من الصفحة الرئيسية اضغط على زر \"امسح منتجك\".",
    how_detail_step2_title: "وجّه الكاميرا للرمز",
    how_detail_step2: "ضع رمز QR داخل الإطار – يعمل حتى في الإضاءة المنخفضة.",
    how_detail_step3_title: "التحقق الفوري",
    how_detail_step3: "يقوم نظام موثوق بمقارنة الرمز مع قاعدة بيانات المنتجات الأصلية.",
    how_detail_step4_title: "استعراض التفاصيل",
    how_detail_step4: "تظهر لك بطاقة المنتج: المكونات، المخاطر، تقييم السلامة.",
    how_detail_caption: "واجهة المسح الضوئي",
    feat1_title: "توثيق فوري",
    feat1: "نتائج خلال ثوانٍ",
    feat2_title: "تحليل المكونات",
    feat2: "تقرير شامل عن المواد",
    feat3_title: "تنبيهات السلامة",
    feat3: "حساسية، مواد ضارة",
    feat4_title: "معلومات موثقة",
    feat4: "قاعدة بيانات محدثة",
    about_badge: "من نحن",
    about_title: "نحو عالم بلا منتجات مغشوشة",
    about_p1: "موثوق منصة رقمية تهدف إلى حماية المستهلك العربي من مخاطر المنتجات غير الأصلية أو الضارة. نؤمن بأن لكل شخص الحق في معرفة ما يضعها على بشرته أو داخل جسده. انطلقنا من رؤية واضحة: الشفافية الكاملة عبر تقنية المسح الضوئي.",
    about_p2: "نعمل مع مختبرات وهيئات رقابية لنضمن لك معلومات دقيقة عن الآلاف من المنتجات الغذائية ومستحضرات التجميل. مهمتنا: ثقة المستهلك أولاً.",
    about_quote: "نحن لا نكتفي بالكشف عن الغش، بل نُعلم المستهلك كيف يقرأ الملصقات ويحمي نفسه.",
    about_ceo: "ريغي ايمان",
    about_ceo_role: "المؤسسة والرئيسة التنفيذية",
    services_title: "خدمات موثوق",
    services_sub: "نقدم أكثر من مجرد مسح QR",
    contact_title: "تواصل مع فريق موثوق",
    contact_sub: "نحن هنا للإجابة عن استفساراتك، اقتراحاتك، أو للإبلاغ عن منتج.",
    contact_address: "غرداية، الجزائر",
    contact_name: "الاسم الكامل",
    contact_email: "البريد الإلكتروني",
    contact_message: "الرسالة",
    contact_placeholder_name: "مثال: سارة أحمد",
    contact_placeholder_msg: "كيف يمكننا مساعدتك؟",
    contact_send: "إرسال الرسالة",
    cta_title: "احمِ نفسك وعائلتك اليوم",
    cta_sub: "جرّب موثوق مجاناً، وامسح أي منتج لتعرف حقيقته.",
    cta_btn: "ابدأ المسح الآن",
    cta_hint: "لا تحتاج تحميل · يعمل مباشرة من المتصفح",
    footer_tagline: "منصة التحقق الذكية للمنتجات. نضمن لك أصالة وسلامة ما تستهلكه.",
    footer_company: "الشركة",
    footer_support: "الدعم",
    footer_download: "التنزيل",
    footer_jobs: "الوظائف",
    footer_faq: "الأسئلة الشائعة",
    footer_privacy: "سياسة الخصوصية",
    footer_terms: "شروط الاستخدام",
    footer_copyright: "© 2025 موثوق - منصة التوثيق الذكية. جميع الحقوق محفوظة.",
    product_status: "حالة المنتج",
    product_original: "✔ أصلي",
    product_not_original: "غير أصلي",
    product_unknown: "غير معروف",
    product_description: "الوصف",
    product_ingredients: "المكونات",
    product_instructions: "تعليمات الاستخدام",
    product_usage_times: "أوقات الاستعمال",
    product_risks: "مخاطر محتملة",
    product_storage: "طريقة التخزين",
    product_expiry: "الصلاحية بعد الفتح",
    product_skin_types: "أنواع البشرة المناسبة",
    product_volume: "الحجم",
    product_contraindications: "موانع الاستخدام",
    product_benefits: "الفوائد",
    product_warnings: "تحذيرات",
    product_alert: "تنبيه",
    batch_label: "رقم الدفعة"
  },
  fr: {
    brand_name: "Mawthooq",
    nav_home: "Accueil",
    nav_about: "Qui sommes-nous",
    nav_services: "Nos services",
    nav_how: "Comment ça marche",
    nav_contact: "Contact",
    nav_scan_btn: "Scannez votre produit",
    hero_title: "Vérifiez vos produits",
    hero_title_highlight: "en quelques secondes",
    hero_sub: "Avec la plateforme Mawthooq, scannez le QR code de tout produit alimentaire ou cosmétique pour connaître son authenticité et sa sécurité. Nous vous protégeons des produits contrefaits et dangereux.",
    hero_scan_btn: "Scanner le produit maintenant",
    hero_how_btn: "Comment ça marche",
    hero_stat1: "Plus de 10 000 produits certifiés",
    hero_stat2: "Haute précision",
    scan_badge: "Scanner",
    scan_title: "Scannez le QR code du produit",
    scan_sub: "Dirigez la caméra vers le code QR sur l'emballage pour vérifier le produit",
    scan_status: "Scan en cours... Placez le code QR dans le cadre",
    scan_result_label: "Résultat du scan :",
    scan_not_found: "Produit non enregistré dans la base de données Mawthooq.",
    scan_again_btn: "Scanner un autre code",
    scan_camera_hint: "Fonctionne mieux en HTTPS ou localhost",
    scan_error_hint: "Vérifiez l'autorisation caméra pour ce site ou essayez un autre navigateur (Chrome / Edge).",
    scan_err_generic: "Une erreur s'est produite. Vérifiez votre connexion ou réessayez plus tard.",
    scan_err_no_camera_support: "Le navigateur ne supporte pas la caméra. Utilisez Chrome ou Safari.",
    scan_err_libs_not_loaded: "Les bibliothèques de scan ne se sont pas chargées. Vérifiez votre connexion.",
    scan_err_video_failed: "Impossible de démarrer la vidéo. Vérifiez l'autorisation d'accès à la caméra.",
    scan_err_permission_denied: "Accès caméra refusé. Autorisez-le depuis les paramètres du navigateur.",
    scan_err_camera_not_found: "Aucune caméra n'a été trouvée.",
    scan_err_camera_unreachable: "Impossible d'accéder à la caméra. Essayez en HTTPS ou un autre navigateur.",
    hero_card_tagline: "Produit alimentaire · Chocolat",
    hero_card_status: "✔ Authentique",
    hero_card_title: "Chocolat noir",
    hero_card_bullet1: "Sans graisses hydrogénées",
    hero_card_bullet2: "Peut contenir des fruits à coque",
    hero_card_verified: "Vérifié via Mawthooq",
    how_badge: "Système intégré",
    how_title: "Comment fonctionne Mawthooq ?",
    how_sub: "Trois étapes simples pour des informations précises sur tout produit",
    how_step1_title: "Ouvrez le scanner",
    how_step1: "Appuyez sur le bouton de scan dans l'application ou le site.",
    how_step2_title: "Scannez le QR",
    how_step2: "Dirigez la caméra vers l'étiquette sur l'emballage.",
    how_step3_title: "Vérifiez et consultez",
    how_step3: "Vous obtenez des infos complètes : ingrédients, risques et mode d'emploi.",
    how_detail_badge: "Guide d'utilisation",
    how_detail_title: "Étapes détaillées de fonctionnement",
    how_detail_step1_title: "Ouvrez le scanner",
    how_detail_step1: "Depuis la page d'accueil, appuyez sur le bouton « Scannez votre produit ».",
    how_detail_step2_title: "Visez le code",
    how_detail_step2: "Placez le QR code dans le cadre – fonctionne même en faible luminosité.",
    how_detail_step3_title: "Vérification instantanée",
    how_detail_step3: "Mawthooq compare le code avec la base de données des produits authentiques.",
    how_detail_step4_title: "Affichage des détails",
    how_detail_step4: "Une fiche produit détaillée s'affiche : ingrédients, risques, niveau de sécurité.",
    how_detail_caption: "Interface de scan",
    feat1_title: "Certification instantanée",
    feat1: "Résultats en secondes",
    feat2_title: "Analyse des ingrédients",
    feat2: "Rapport détaillé sur les substances",
    feat3_title: "Alertes sécurité",
    feat3: "Allergènes, substances interdites",
    feat4_title: "Données certifiées",
    feat4: "Base de données à jour",
    about_badge: "Qui sommes-nous",
    about_title: "Vers un monde sans produits contrefaits",
    about_p1: "Mawthooq est une plateforme numérique qui vise à protéger le consommateur des produits non authentiques ou dangereux. Nous croyons que chacun a le droit de savoir ce qu'il met sur sa peau ou dans son corps. Notre vision : une transparence totale grâce au scan.",
    about_p2: "Nous travaillons avec des laboratoires et des autorités pour vous garantir des informations précises sur des milliers de produits alimentaires et cosmétiques. Notre mission : la confiance du consommateur d'abord.",
    about_quote: "Nous ne nous contentons pas de détecter la contrefaçon, nous apprenons au consommateur à lire les étiquettes et à se protéger.",
    about_ceo: "Righi Iman",
    about_ceo_role: "Fondatrice et CEO",
    services_title: "Services Mawthooq",
    services_sub: "Bien plus qu'un simple scan QR",
    contact_title: "Contactez l'équipe Mawthooq",
    contact_sub: "Nous sommes là pour vos questions, suggestions ou signalements.",
    contact_address: "Ghardaïa, Algérie",
    contact_name: "Nom complet",
    contact_email: "E-mail",
    contact_message: "Message",
    contact_placeholder_name: "Ex. : Sara Ahmed",
    contact_placeholder_msg: "Comment pouvons-nous vous aider ?",
    contact_send: "Envoyer le message",
    cta_title: "Protégez-vous et votre famille aujourd'hui",
    cta_sub: "Essayez Mawthooq gratuitement et scannez tout produit pour en connaître l'authenticité.",
    cta_btn: "Commencer à scanner",
    cta_hint: "Aucun téléchargement · Fonctionne dans le navigateur",
    footer_tagline: "Plateforme de vérification des produits. Authenticité et sécurité garanties.",
    footer_company: "Entreprise",
    footer_support: "Support",
    footer_download: "Télécharger",
    footer_jobs: "Carrières",
    footer_faq: "FAQ",
    footer_privacy: "Politique de confidentialité",
    footer_terms: "Conditions d'utilisation",
    footer_copyright: "© 2025 Mawthooq - Plateforme de certification. Tous droits réservés.",
    product_status: "État du produit",
    product_original: "✔ Authentique",
    product_not_original: "Non authentique",
    product_unknown: "Inconnu",
    product_description: "Description",
    product_ingredients: "Ingrédients",
    product_instructions: "Mode d'emploi",
    product_usage_times: "Moments d'utilisation",
    product_risks: "Risques potentiels",
    product_storage: "Conservation",
    product_expiry: "Utilisation après ouverture",
    product_skin_types: "Types de peau adaptés",
    product_volume: "Volume",
    product_contraindications: "Contre-indications",
    product_benefits: "Avantages",
    product_warnings: "Avertissements",
    product_alert: "Alerte",
    batch_label: "N° de lot"
  },
  en: {
    brand_name: "Mawthooq",
    nav_home: "Home",
    nav_about: "About us",
    nav_services: "Services",
    nav_how: "How it works",
    nav_contact: "Contact",
    nav_scan_btn: "Scan your product",
    hero_title: "Verify your products",
    hero_title_highlight: "in seconds",
    hero_sub: "With the Mawthooq platform, scan the QR code on any food or cosmetic product to check its authenticity and safety. We protect you from counterfeit and dangerous products.",
    hero_scan_btn: "Scan product now",
    hero_how_btn: "How it works",
    hero_stat1: "Over 10,000 certified products",
    hero_stat2: "High accuracy",
    scan_badge: "Scanner",
    scan_title: "Scan the product QR code",
    scan_sub: "Point the camera at the QR code on the package to verify the product",
    scan_status: "Scanning... Place the QR code in the frame",
    scan_result_label: "Scan result:",
    scan_not_found: "Product not registered in Mawthooq database.",
    scan_again_btn: "Scan another code",
    scan_camera_hint: "Works best on HTTPS or localhost",
    scan_error_hint: "Make sure you allowed camera access, or try another browser (Chrome / Edge).",
    scan_err_generic: "An error occurred. Check your connection or try again later.",
    scan_err_no_camera_support: "This browser does not support the camera. Use Chrome or Safari.",
    scan_err_libs_not_loaded: "Scanner libraries were not loaded. Check your internet connection.",
    scan_err_video_failed: "Could not start video. Please allow camera access.",
    scan_err_permission_denied: "Camera permission was denied. Allow it from browser settings.",
    scan_err_camera_not_found: "No camera was found.",
    scan_err_camera_unreachable: "Could not access the camera. Try HTTPS or another browser.",
    hero_card_tagline: "Food product · Chocolate",
    hero_card_status: "✔ Original",
    hero_card_title: "Dark chocolate",
    hero_card_bullet1: "Free from hydrogenated fats",
    hero_card_bullet2: "May contain nuts",
    hero_card_verified: "Verified via Mawthooq",
    how_badge: "Integrated system",
    how_title: "How does Mawthooq work?",
    how_sub: "Three simple steps for accurate information on any product",
    how_step1_title: "Open the scanner",
    how_step1: "Tap the scan button in the app or website.",
    how_step2_title: "Scan the QR code",
    how_step2: "Point the camera at the label on the package.",
    how_step3_title: "Verify and view",
    how_step3: "Get full details: ingredients, risks, and usage instructions.",
    how_detail_badge: "Usage guide",
    how_detail_title: "Step‑by‑step workflow",
    how_detail_step1_title: "Open the scanner",
    how_detail_step1: "From the home page, tap the “Scan your product” button.",
    how_detail_step2_title: "Point at the code",
    how_detail_step2: "Place the QR code inside the frame – works even in low light.",
    how_detail_step3_title: "Instant verification",
    how_detail_step3: "Mawthooq compares the code with the database of authentic products.",
    how_detail_step4_title: "View full details",
    how_detail_step4: "You see a full product card: ingredients, risks, safety level.",
    how_detail_caption: "Scan interface",
    feat1_title: "Instant verification",
    feat1: "Results in seconds",
    feat2_title: "Ingredient analysis",
    feat2: "Full report on substances",
    feat3_title: "Safety alerts",
    feat3: "Allergens, banned substances",
    feat4_title: "Certified data",
    feat4: "Up-to-date database",
    about_badge: "About us",
    about_title: "Towards a world without counterfeit products",
    about_p1: "Mawthooq is a digital platform aimed at protecting consumers from non-authentic or harmful products. We believe everyone has the right to know what they put on their skin or in their body. Our vision: full transparency through scanning.",
    about_p2: "We work with labs and authorities to give you accurate information on thousands of food and cosmetic products. Our mission: consumer trust first.",
    about_quote: "We don't just detect counterfeits; we teach consumers how to read labels and protect themselves.",
    about_ceo: "Righi Iman",
    about_ceo_role: "Founder & CEO",
    services_title: "Mawthooq services",
    services_sub: "More than just QR scanning",
    contact_title: "Contact Mawthooq team",
    contact_sub: "We're here for your questions, suggestions, or product reports.",
    contact_address: "Ghardaia, Algeria",
    contact_name: "Full name",
    contact_email: "Email",
    contact_message: "Message",
    contact_placeholder_name: "e.g. Sara Ahmed",
    contact_placeholder_msg: "How can we help you?",
    contact_send: "Send message",
    cta_title: "Protect yourself and your family today",
    cta_sub: "Try Mawthooq for free and scan any product to know the truth.",
    cta_btn: "Start scanning now",
    cta_hint: "No download required · Works in the browser",
    footer_tagline: "Smart product verification platform. We guarantee authenticity and safety.",
    footer_company: "Company",
    footer_support: "Support",
    footer_download: "Download",
    footer_jobs: "Careers",
    footer_faq: "FAQ",
    footer_privacy: "Privacy policy",
    footer_terms: "Terms of use",
    footer_copyright: "© 2025 Mawthooq - Verification platform. All rights reserved.",
    product_status: "Product status",
    product_original: "✔ Original",
    product_not_original: "Not original",
    product_unknown: "Unknown",
    product_description: "Description",
    product_ingredients: "Ingredients",
    product_instructions: "Usage instructions",
    product_usage_times: "Usage times",
    product_risks: "Potential risks",
    product_storage: "Storage",
    product_expiry: "Use after opening",
    product_skin_types: "Suitable skin types",
    product_volume: "Volume",
    product_contraindications: "Contraindications",
    product_benefits: "Benefits",
    product_warnings: "Warnings",
    product_alert: "Notice",
    batch_label: "Batch number"
  }
};

window.MAWTHOOQ_LANG = localStorage.getItem('mawthooq_lang') || 'ar';

function mawthooqApplyLang(lang) {
  if (!window.MAWTHOOQ_T || !window.MAWTHOOQ_T[lang]) lang = 'ar';
  window.MAWTHOOQ_LANG = lang;
  localStorage.setItem('mawthooq_lang', lang);
  var T = window.MAWTHOOQ_T[lang];
  var root = document.documentElement;
  root.setAttribute('lang', lang);
  root.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
  document.body.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var k = el.getAttribute('data-i18n');
    if (T[k]) el.textContent = T[k];
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el) {
    var k = el.getAttribute('data-i18n-placeholder');
    if (T[k]) el.placeholder = T[k];
  });
  var titleMap = { ar: 'موثوق – تحقق من منتجاتك فوراً', fr: 'Mawthooq – Vérifiez vos produits', en: 'Mawthooq – Verify your products' };
  document.title = titleMap[lang] || titleMap.ar;
  if (typeof window.mawthooqOnLangChange === 'function') window.mawthooqOnLangChange(lang);
}
